environment:
    decrypt_pass:
     secure: lK0NTOd98gxMkMDvj3IUWCAW/3vC8X8mqSlGGwQ16dH/yGg84/2zmuFzGG9W8R1w
branches:
    only:
    - v0.47
version: 1.0.{build}
os: Visual Studio 2013
install:
- choco install nant
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
- ps: appveyor-tools\secure-file -decrypt C:\projects\ikvm\tools\ikvm-key.snk.enc -secret "$env:decrypt_pass"
- set PATH=C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools;%PATH%
- cmd: sn -i C:\projects\ikvm\tools\ikvm-key.snk ikvm-key
before_build:
- refreshenv
- set JAVA_HOME=C:\Program Files\Java\jdk1.6.0
- set PATH=C:\Program Files\Java\jdk1.6.0\bin;%PATH%
- ps: wget http://www.frijters.net/openjdk6-b22-stripped.zip -OutFile openjdk6-b22-stripped.zip
- ps: Expand-Archive .\openjdk6-b22-stripped.zip -DestinationPath ..\
build_script:
- nant signed
after_build:
- nuget pack IKVM.0.47.0.1.nuspec
artifacts:
- path: IKVM.0.47.0.1.nupkg
test: off
